global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'todo-service'
    metrics_path: /q/metrics
    static_configs:
      - targets: ['todo-service:8082']

  - job_name: 'web-service'
    metrics_path: /q/metrics
    static_configs:
      - targets: ['web-service:8080']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
